language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

script:
  - ./gradlew clean assembleDebug -x fabricGenerateResourcesDebug

branches:
  except:
    - gh-pages